# Generated by Django 5.1.4 on 2025-01-03 04:34

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='Unknown', max_length=30)),
                ('children', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('it', 'Italian')], default='Spanish', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('date_joined', models.DateField(db_default=django.db.models.functions.datetime.Now())),
                ('wordlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordlist', to='words.theme')),
            ],
            options={
                'verbose_name_plural': 'words',
                'db_table': 'words_table',
                'ordering': ['-date_joined'],
            },
        ),
    ]
