# Generated by Django 5.1.4 on 2024-12-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('language', models.CharField(max_length=30)),
                ('size', models.IntegerField()),
                ('theme', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'word_fun',
            },
        ),
    ]
