# Generated by Django 5.1.4 on 2024-12-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'get_latest_by': 'order_date'},
        ),
        migrations.AlterModelTableComment(
            name='word',
            table_comment='Table for words',
        ),
    ]
