# Generated by Django 5.1.4 on 2025-02-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='created_at',
        ),
    ]
