# Generated by Django 5.1.4 on 2025-02-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_rename_wordlist_word_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
