# Generated by Django 5.1.4 on 2025-02-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_word_word_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word_user',
            new_name='created_by',
        ),
    ]
