# Generated by Django 5.1.4 on 2025-02-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
