# Generated by Django 5.1.4 on 2024-12-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_word_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['size'], 'verbose_name_plural': 'words'},
        ),
    ]
