# Generated by Django 5.1.4 on 2024-12-22 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_alter_word_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['date_joined'], 'verbose_name_plural': 'words'},
        ),
        migrations.RemoveField(
            model_name='word',
            name='size',
        ),
        migrations.AddField(
            model_name='word',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 12, 22, 18, 3, 31, 405838, tzinfo=datetime.timezone.utc)),
        ),
    ]
