# Generated by Django 5.1.4 on 2024-12-22 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_alter_word_options_remove_word_size_word_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 12, 22, 18, 4, 21, 472779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='word',
            table=None,
        ),
    ]
