# Generated by Django 5.1.4 on 2024-12-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_alter_word_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='name',
            new_name='word',
        ),
    ]
