# Generated by Django 5.1.4 on 2024-12-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_rename_name_word_word'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='word',
            table='words_table',
        ),
    ]
