# Generated by Django 5.1.4 on 2024-12-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_alter_word_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('it', 'Italian')], max_length=2),
        ),
    ]
